# Generated by Django 3.1.7 on 2021-04-13 19:18

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210413_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=app.models.ListField(),
        ),
    ]
